ALCOHOLIC:
  loss: huber
  max_features: auto
  min_samples_split: 2
  min_weight_fraction_leaf: 0.1
  n_estimators: 500
  n_iter_no_change: 5
  random_state: 12
CANTALOUPE, HONEYDEW MELON:
  loss: huber
  max_features: sqrt
  min_samples_split: 2
  min_weight_fraction_leaf: 0.1
  n_estimators: 500
  n_iter_no_change: 10
  random_state: 12
METALLIC:
  loss: huber
  max_features: auto
  min_samples_split: 2
  min_weight_fraction_leaf: 0.5
  n_estimators: 100
  n_iter_no_change: 25
  random_state: 12
MOTHBALLS:
  loss: squared_error
  max_features: sqrt
  min_samples_split: 2
  min_weight_fraction_leaf: 0.1
  n_estimators: 50
  n_iter_no_change: 25
  random_state: 12
PINEAPPLE:
  loss: squared_error
  max_features: auto
  min_samples_split: 2
  min_weight_fraction_leaf: 0.1
  n_estimators: 50
  n_iter_no_change: 10
  random_state: 12
RAISINS:
  loss: quantile
  max_features: auto
  min_samples_split: 2
  min_weight_fraction_leaf: 0.5
  n_estimators: 50
  n_iter_no_change: 25
  random_state: 12
SEASONING FOR MEAT:
  loss: squared_error
  max_features: sqrt
  min_samples_split: 2
  min_weight_fraction_leaf: 0.1
  n_estimators: 50
  n_iter_no_change: 10
  random_state: 12
